/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mds.app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.LinkedList;
import java.util.concurrent.Flow;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.swing.*;

public class App {

    public static void main(String[] args) {
        LinkedList<Integer> queue = new LinkedList<>();
        Frame mainFrame = new Frame();
        Panel panel = new Panel(mainFrame);
        JPanel buttonPanel = new JPanel();

        buttonPanel.setBackground(Color.WHITE);
        buttonPanel.setSize(1280, 250);
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 20));

        Frame controlFrame = new Frame();
        Panel controlPanel = new Panel(controlFrame);
        controlFrame.add(controlPanel, BorderLayout.CENTER);
        JButton addBtn = new JButton("add");
        JButton removeBtn = new JButton("next");
        addBtn.setFont(new Font("Arial", Font.BOLD, 40));
        removeBtn.setFont(new Font("Arial", Font.BOLD, 40));

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int totalWidth = mainFrame.getWidth() + controlFrame.getWidth();
        int gap = 20;
        int x = 0;
        int y = (screenSize.height - mainFrame.getHeight()) / 2;
        mainFrame.setLocation(x, y);
        controlFrame.setLocation(x + mainFrame.getWidth() + gap, y);

        controlFrame.add(buttonPanel, BorderLayout.PAGE_END);
        buttonPanel.add(addBtn);
        buttonPanel.add(removeBtn);

        NextToBeServedTimer nextCustomer = new NextToBeServedTimer(queue);
        AtomicBoolean isCustomerSet = new AtomicBoolean(false);
        mainFrame.add(nextCustomer, BorderLayout.PAGE_START);
        mainFrame.revalidate();
        removeBtn.addActionListener(e -> {
            String s = controlFrame.popQueue(queue, controlPanel);
            mainFrame.removeLabel(panel);
            nextCustomer.customerToBeServed.setText("Next Customer: " + s);
            nextCustomer.timeRemaining.set(30);
            mainFrame.repaint();
            mainFrame.revalidate();

        });

        JLabel customerToBeServed = new JLabel();

        JLabel placeholder = new JLabel("Next Customer!");
        placeholder.setFont(new Font("Arial", Font.BOLD, 40));
        placeholder.setBounds(0, -10, 1280, 400);

        // mainFrame.add(placeholder, BorderLayout.PAGE_START);
        // mainFrame.add(new NextToBeServedTimer(queue), BorderLayout.PAGE_START);
        mainFrame.add(panel, BorderLayout.PAGE_END);

        addBtn.addActionListener(e -> {
            mainFrame.addQueue(queue, panel);
            controlFrame.updatePanel(queue, controlPanel);
        });

    }
}
