/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mds.app;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.LinkedList;

import javax.swing.*;
import javax.swing.border.EmptyBorder;

public class App {

	public static void main(String[] args) {
		LinkedList<Integer> queue = new LinkedList<>();
		Frame mainFrame = new Frame("Main Panel");
		Panel panel = new Panel(mainFrame);
		JPanel buttonPanel = new JPanel();

		buttonPanel.setBackground(Color.WHITE);
		buttonPanel.setSize(1280, 250);
		buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 20));

		Frame controlFrame = new Frame("Control Panel");
		JPanel controlQueue = new JPanel();
		JButton addBtn = new JButton("add");
		JButton removeBtn = new JButton("next");
		JButton closeBtn = new JButton("close");
		addBtn.setFont(new Font("Arial", Font.BOLD, 40));
		removeBtn.setFont(new Font("Arial", Font.BOLD, 40));
		closeBtn.setFont(new Font("Arial", Font.BOLD, 40));

		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

		int gap = 20;
		int x = 0;
		int y = (screenSize.height - mainFrame.getHeight()) / 2;
		mainFrame.setLocation(x, y);
		controlFrame.setLocation(x + mainFrame.getWidth() + gap, y);

		buttonPanel.add(addBtn);
		buttonPanel.add(removeBtn);
		buttonPanel.add(closeBtn);

		closeBtn.addActionListener(e -> {
			int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit?",
					JOptionPane.YES_NO_OPTION);

			if (response == JOptionPane.YES_OPTION) {
				System.exit(0);
			}
		});

		Panel controlPanel = new Panel(controlFrame);
		NextPanel nextControl = new NextPanel();
		controlPanel.add(nextControl);
		controlPanel.add(controlQueue);
		controlFrame.add(buttonPanel, BorderLayout.PAGE_END);
		controlFrame.add(controlPanel, BorderLayout.CENTER);

		NextToBeServedTimer nextCustomerMain = new NextToBeServedTimer();
		nextCustomerMain.time.setVisible(false);
		JPanel header = new JPanel();
		header.setPreferredSize(new Dimension(0, 70));
		header.setBackground(new Color(0x057523));
		header.setLayout(new BorderLayout());
		header.setBorder(BorderFactory.createRaisedSoftBevelBorder());
		mainFrame.add(header, BorderLayout.NORTH);

		JLabel title = new JLabel("Queueing System");
		title.setFont(new Font("Arial", Font.BOLD, 30));
		title.setForeground(Color.WHITE);
		title.setBorder(new EmptyBorder(5, 5, 5, 5));
		header.add(title, BorderLayout.EAST);
		header.repaint();

		JLabel next = new JLabel("Now Serving");
		next.setBorder(new EmptyBorder(10, 20, 10, 20));
		next.setFont(new Font("Arial", Font.BOLD, 60));

		// mainFrame.add(nextCustomerMain, BorderLayout.WEST);

		NextPanel nextPanel = new NextPanel();
		panel.add(nextPanel);
		JPanel queuePanel = new JPanel();
		panel.add(queuePanel);
		mainFrame.add(panel, BorderLayout.CENTER);

		mainFrame.revalidate();
		mainFrame.repaint();
		removeBtn.addActionListener(e -> {
			String s = controlFrame.popQueue(queue, controlQueue);
			mainFrame.removeLabel(queuePanel);
			nextPanel.nextCustomer.setCustomerToBeServed(s);
			nextControl.nextCustomer.setCustomerToBeServed(s);
			nextControl.add(nextControl.nextCustomer.time);
			mainFrame.repaint();
			mainFrame.revalidate();

		});

		addBtn.addActionListener(e -> {
			mainFrame.addQueue(queue, queuePanel);
			controlFrame.updatePanel(queue, controlQueue);
		});

	}
}
